apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-block-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
